import Joi from "joi";

export const createProductSchema = Joi.object({
  name: Joi.string().required().messages({
    "string.empty": "Product name is required",
    "any.required": "Product name is required",
  }),
  unit: Joi.string(),
  size: Joi.string(),
  origin: Joi.string(),
  countrySale: Joi.string(),
  productType: Joi.string(),
  packagingType: Joi.string(),
  gpc: Joi.string(),
  price: Joi.number(),
  description: Joi.string(),
  status: Joi.string(),
  gtin: Joi.string(),
  sku: Joi.string(),
  brandName: Joi.string(),
  batch: Joi.string(),
  uniqueProductCode: Joi.string(),
  expiryDate: Joi.date(),
  packagingDate: Joi.date(),
  quantity: Joi.number().integer(),
  gln: Joi.string(),
  binLocation: Joi.string(),
  categoryId: Joi.string(),
});

export const updateProductSchema = Joi.object({
  name: Joi.string().messages({
    "string.empty": "Product name cannot be empty",
  }),
  unit: Joi.string(),
  size: Joi.string(),
  origin: Joi.string(),
  countrySale: Joi.string(),
  productType: Joi.string(),
  packagingType: Joi.string(),
  gpc: Joi.string(),
  price: Joi.number(),
  description: Joi.string(),
  status: Joi.string(),
  gtin: Joi.string(),
  sku: Joi.string(),
  brandName: Joi.string(),
  batch: Joi.string(),
  uniqueProductCode: Joi.string(),
  expiryDate: Joi.date(),
  packagingDate: Joi.date(),
  quantity: Joi.number().integer(),
  gln: Joi.string(),
  binLocation: Joi.string(),
  categoryId: Joi.string(),
}).min(1);
